# Example configuration with one validator and one full node
# Todo: document this fully
[global]
gaiad_binary="$GOPATH/bin/gaiad"
ports_start_at=27000
home_dir="$HOME/.gm"
auto_maintain_config=true

[validator1]
#auto_maintain_config=false
fake_entry=""

[node1]
network="validator1"
