version: '3'

services:

  ibc-0:
    container_name: ibc-0
    image: "informaldev/ibc-0:v3.0.0"
#    logging:
#      driver: none
    stdin_open: true
    tty: true
    entrypoint: "gaiad start --home=/chain --grpc.address=ibc-0:9090  --pruning=nothing"
    networks:
      relaynet:
        ipv4_address: 172.25.0.10

  ibc-1:
    container_name: ibc-1
    image: "informaldev/ibc-1:v3.0.0"
#    logging:
#      driver: none
    stdin_open: true
    tty: true
    entrypoint: "gaiad start --home=/chain --grpc.address=ibc-1:9090 --pruning=nothing"
    networks:
      relaynet:
        ipv4_address: 172.25.0.11

  relayer:
    depends_on:
      - ibc-0
      - ibc-1
    container_name: relayer
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: ci/relayer.Dockerfile
      args:
        RELEASE: v3.0.0
    environment:
      - CHAIN_A=ibc-0
      - CHAIN_A_HOME=/data/ibc-0
      - CHAIN_A_PORT=26657
      - CHAIN_B=ibc-1
      - CHAIN_B_HOME=/data/ibc-1
      - CHAIN_B_PORT=26657
      - CONFIG=simple_config.toml
      - RELAYER_DIR=/relayer
      - RELEASE=v3.0.0
    networks:
      relaynet:
        ipv4_address: 172.25.0.12

networks:
  relaynet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16