[book]
authors = ["Informal Systems Inc."]
language = "en"
multilingual = false
src = "src"
title = "Hermes (IBC Relayer CLI) Documentation"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]

# Uncomment to trigger the link check
# [output.linkcheck]

[preprocessor.template]

