name: End to End testing
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v2
      -  name: Build relayer image
         run: docker-compose -f docker-compose.yml build relayer
      -  name: Start chains and relayer
         run: docker-compose -f docker-compose.yml up -d ibc-0 ibc-1 relayer
      -  name: Run relayer workflow
         run: docker exec relayer /bin/sh -c /relayer/setup_relayer.sh
