name: Guide Template Checker
on:
  pull_request:
    paths:
      - .github/workflows/guide-templates.yaml
      - crates/relayer-cli/**
      - scripts/**
      - tools/check-guide/**
      - guide/src/templates/**

  push:
    branches: master
    paths:
      - .github/workflows/guide-templates.yaml
      - crates/relayer-cli/**
      - scripts/**
      - tools/check-guide/**
      - guide/src/templates/**

# Cancel previous runs of this workflow when a new commit is added to the PR, branch or tag
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  template-checker:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install Protoc
        uses: heliaxdev/setup-protoc@v2
        with:
          version: "25.0"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check templates
        run: bash scripts/auto_gen_templates.sh --mode "check"
      - uses: actions-rs/cargo@v1
        name: Check guide
        with:
          command: run
          args: --manifest-path tools/check-guide/Cargo.toml
