name: Guide Template Checker
on:
  pull_request:
    paths:
      - .github/workflows/guide-templates.yaml
      - crates/**
      - scripts/**
      - tools/check-guide/**

  push:
    branches: master
    paths:
      - .github/workflows/guide-templates.yaml
      - crates/**
      - scripts/**
      - tools/check-guide/**
      
jobs:
  template-checker:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: check templates
        run: bash scripts/auto_gen_templates.sh --mode "check"
      - uses: actions-rs/cargo@v1
        with:
          command: run
          args: -p check-guide
