name: Hermes Guide

on:
  push:
    branches:
      - master
    paths:
      - guide/**
  pull_request:
    paths:
      - guide/**

jobs:
  guide:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdbook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "0.4.7"

      - name: Setup mdbook-mermaid
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: mdbook-mermaid

      - name: Setup mdbook-toc
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: mdbook-toc

      - name: Build guide
        run: |
          cd guide
          mdbook build

      # Only deploy guide when pushing to master
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./guide/book
