name: Misbehaviour
on:
  pull_request:
    paths:
      - .github/workflows/misbehaviour.yaml
      - Cargo.toml
      - Cargo.lock
      - flake.nix
      - flake.lock
      - ci/**
      - scripts/**
      - crates/**
  push:
    branches: master
    paths:
      - .github/workflows/misbehaviour.yaml
      - Cargo.toml
      - Cargo.lock
      - flake.nix
      - flake.lock
      - ci/**
      - scripts/**
      - crates/**

env:
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_DEV_DEBUG: 1
  CARGO_PROFILE_RELEASE_DEBUG: 1
  RUST_BACKTRACE: short
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10

# Cancel previous runs of this workflow when a new commit is added to the PR, branch or tag
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  light-client-attack:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        chain:
          - package: gaia14
            command: gaiad
            account_prefix: cosmos
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Use cachix cache
        uses: cachix/cachix-action@v14
        with:
          name: cosmos
      - name: Install sconfig
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: freshautomations/sconfig
          platform: linux
          arch: amd64
          extension-matching: disable
          rename-to: sconfig
          chmod: 0755
      - name: Install stoml
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: freshautomations/stoml
          platform: linux
          arch: amd64
          extension-matching: disable
          rename-to: stoml
          chmod: 0755
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Use Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Build Hermes
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: Run test
        working-directory: ci/misbehaviour
        run: |
          nix shell .#${{ matrix.chain.package }} -c bash misbehaviour_test.sh

  ics-light-client-attack:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        chain:
          - package: interchain-security
            account_prefix: cosmos
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Use cachix cache
        uses: cachix/cachix-action@v14
        with:
          name: cosmos
      - name: Install sconfig
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: freshautomations/sconfig
          platform: linux
          arch: amd64
          extension-matching: disable
          rename-to: sconfig
          chmod: 0755
      - name: Install stoml
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: freshautomations/stoml
          platform: linux
          arch: amd64
          extension-matching: disable
          rename-to: stoml
          chmod: 0755
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Use Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Build Hermes
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: Run test
        working-directory: ci/misbehaviour-ics
        run: |
          nix shell .#cometbft .#${{ matrix.chain.package }} -c bash light_client_attack_test.sh

  ics-light-client-attack-freeze:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        chain:
          - package: interchain-security
            account_prefix: cosmos
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Use cachix cache
        uses: cachix/cachix-action@v14
        with:
          name: cosmos
      - name: Install sconfig
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: freshautomations/sconfig
          platform: linux
          arch: amd64
          extension-matching: disable
          rename-to: sconfig
          chmod: 0755
      - name: Install stoml
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: freshautomations/stoml
          platform: linux
          arch: amd64
          extension-matching: disable
          rename-to: stoml
          chmod: 0755
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Use Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Build Hermes
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: Run test
        working-directory: ci/misbehaviour-ics
        run: |
          nix shell .#${{ matrix.chain.package }} -c bash light_client_attack_freeze_test.sh


  ics-double-sign:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        chain:
          - package: interchain-security
            account_prefix: cosmos
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Use cachix cache
        uses: cachix/cachix-action@v14
        with:
          name: cosmos
      - name: Install sconfig
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: freshautomations/sconfig
          platform: linux
          arch: amd64
          extension-matching: disable
          rename-to: sconfig
          chmod: 0755
      - name: Install stoml
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: freshautomations/stoml
          platform: linux
          arch: amd64
          extension-matching: disable
          rename-to: stoml
          chmod: 0755
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Use Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Build Hermes
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: Run test
        working-directory: ci/misbehaviour-ics
        run: |
          nix shell .#${{ matrix.chain.package }} -c bash double_sign_test.sh

