name: no_std check
on:
  pull_request:
    paths:
      - .github/workflows/rust.yml
      - Cargo.toml
      - ci/**
      - proto/**
      - modules/**
  push:
    branches: master
    paths:
      - .github/workflows/rust.yml
      - Cargo.toml
      - ci/**
      - proto/**
      - modules/**

jobs:
  check-no-std-panic-conflict:
    name: Check no_std panic conflict
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: |
          cd ci/no-std-check
          make check-panic-conflict

  check-substrate:
    name: Check no_std substrate support
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-09-01
          target: wasm32-unknown-unknown
          override: true
      - run: |
          cd ci/no-std-check
          make check-substrate
